apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - secrets.yaml
  - store-api.yaml
  - order-service.yaml
  - inventory-worker.yaml
  - store-api-serviceprofile.yaml
