apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  STORE_API_CONN: "Server=sqlserver,1433;Database=StoreApiDb;User Id=sa;Password=ChangeMeNow123!;TrustServerCertificate=True"
  ORDER_SERVICE_CONN: "Host=postgres;Port=5432;Database=OrdersDb;Username=admin;Password=ChangeMeNow123!"
  INVENTORY_WORKER_CONN: "Server=sqlserver,1433;Database=StoreApiDb;User Id=sa;Password=ChangeMeNow123!;TrustServerCertificate=True"
